//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAB_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksWithAuthorsAndCategory
    {
        public string Title { get; set; }
        public string Name { get; set; }
        public string Category_name { get; set; }
    }
}
